MahjongBuddy/MahjongBuddy/Controllers/GameController.cs
using MahjongBuddy.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace MahjongBuddy.Controllers
{
    public class GameController : AppController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Canvas()
        {
            return View();
        }
    }
}

MahjongBuddy/MahjongBuddy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="app">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MahjongBuddy</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.4/angular.min.js"></script>
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" media="screen"/>
    <link rel="stylesheet" href="~/Content/bootstrap-theme.min.css" media="screen" />
    <link rel="stylesheet" href="~/Content/bootstrap-toggle.min.css" media="screen" />
    <link rel="stylesheet" href="~/Content/animate.min.css" media="screen" />
    <script src="~/Scripts/bootstrap.min.js"></script>    
    <script src="~/Scripts/app.js"></script>
    <script src="~/Scripts/controller.js"></script>
    <script src="~/Scripts/bootstrap-toggle.min.js"></script>
    <script src="~/Scripts/match-media.js"></script>
    <script src="~/Scripts/toggle-checkbox.js"></script>
    <script src="~/Scripts/ngDraggable.js"></script>
    <script src="~/Scripts/angular-animate-1.4.4.js"></script>
    <script src="~/Scripts/mjService.js"></script>
    <script src="~/Scripts/signalrService.js"></script>

    @RenderSection("head", required: false)
</head>
<body>
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("MahjongBuddy", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Play", "Index", "Game")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MahjongBuddy</p>
        </footer>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>